[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
libs = ["lib", "../../stellar/contracts/lib"]
remappings = [
    "@openzeppelin/contracts/=../../stellar/contracts/lib/openzeppelin-contracts/contracts/",
    "forge-std/=../../stellar/contracts/lib/forge-std/src/"
]
